package WebCrawler;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.net.URL;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Set;

/**
 *
 * @author chabineza
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form Canvas
     *
     */
    private HashMap<String, Set<URL>> documentCache;
    private HashMap<String, LinkedList<URL>> indexCache;
    private String keyWord;

    public UserInterface() {
        initComponents();
        this.jPanel1.setVisible(true);
        documentCache  = (HashMap<String, Set<URL>>) Cache.readObject("documentCache.ser");
        indexCache  = (HashMap<String, LinkedList<URL>>) Cache.readObject("indexCache.ser");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchKeyWordLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        keyWordField = new javax.swing.JTextField();
        documentSearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outPutTextPane = new javax.swing.JTextPane();
        indexSearchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchKeyWordLabel.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        searchKeyWordLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchKeyWordLabel.setText("Search String");
        searchKeyWordLabel.setFocusCycleRoot(true);
        searchKeyWordLabel.setFocusTraversalPolicyProvider(true);

        progressBar.setToolTipText("");
        progressBar.setString("0");
        progressBar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                progressBarStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        keyWordField.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        documentSearchButton.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        documentSearchButton.setText("Document Search");
        documentSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentSearchButtonActionPerformed(evt);
            }
        });

        outPutTextPane.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(outPutTextPane);

        indexSearchButton.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        indexSearchButton.setText("Index Search");
        indexSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexSearchButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel1.setText("Search Results");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchKeyWordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(indexSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(documentSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(keyWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchKeyWordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indexSearchButton)
                    .addComponent(documentSearchButton))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        searchKeyWordLabel.getAccessibleContext().setAccessibleDescription("searchStr");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void documentSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentSearchButtonActionPerformed
        keyWord = keyWordField.getText().toLowerCase();
        if (keyWord == null || keyWord.equals("")) {
            System.out.println("Please enter a key word to search");
        } else {
            outPutTextPane.setVisible(true);
            new Thread() {
                @Override
                public void run() {
                    
                    String overAll = "";
                    Set<URL> set;
                    DocumentSearch docSearch  = new DocumentSearch(keyWord);
                    set = docSearch.search(documentCache);
                    if (set != null) {
                        for (URL url : set) {
                            overAll += url.toString() + '\n';
                        }
                    }
                    outPutTextPane.setText(overAll);
                }
            }.start();
        }
        //searchAndUpdate("documentCache.ser");
    }//GEN-LAST:event_documentSearchButtonActionPerformed

    private void progressBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_progressBarStateChanged
        // TODO add your handling code here:  
    }//GEN-LAST:event_progressBarStateChanged

    private void indexSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexSearchButtonActionPerformed
        keyWord = keyWordField.getText().toLowerCase();
        if (keyWord == null || keyWord.equals("")) {
            System.out.println("Please enter a key word to search");
        } else {
            new Thread() {
                @Override
                public void run() {
                    String overAll = "";
                    LinkedList<URL> list;
                    IndexSearch indexSearch  = new IndexSearch(keyWord);
                    list = indexSearch.search(indexCache);
                    if (list != null) {
                        for (URL url : list) {
                            overAll += url.toString() + '\n';
                        }
                    }
                    outPutTextPane.setText(overAll);
                }
            }.start();
        }
        
    }//GEN-LAST:event_indexSearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton documentSearchButton;
    private javax.swing.JButton indexSearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keyWordField;
    private javax.swing.JTextPane outPutTextPane;
    public javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel searchKeyWordLabel;
    // End of variables declaration//GEN-END:variables

   
    
}
